#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../perl_lib";

use RTF::TEXT::Converter;
use Pod::Usage;
use Getopt::Long;

=head1 NAME

rtf2txt - extract plain text from .rtf files

=head1 SYNOPSIS

rtf2txt <input.doc> <output.txt | ->

=cut

use strict;
use warnings;

my(
	$opt_help,
);

GetOptions(
	'help' => \$opt_help,
) or pod2usage();

pod2usage(1) if $opt_help;
pod2usage() if @ARGV != 2;

my( $fh, $ofh );
-r $ARGV[0] or die "Can't read file $ARGV[0]";
open( $fh, "<", $ARGV[0] );

if( $ARGV[1] eq '-' )
{
	$ofh = \*STDOUT;
}
else
{
	open($ofh, ">", $ARGV[1]) or die "Error opening $ARGV[1]: $!";
}

binmode($ofh, ":utf8");

my $object = RTF::TEXT::Converter->new(
        output => $ofh
);
$object->parse_stream( $fh );

=head1 COPYRIGHT AND LICENSE

=begin COPYRIGHT_AND_LICENSE

Copyright University of Southampton under the GNU Lesser General Public License. See README at https://github.com/eprints/eprints3.5 for further information.

EPrints 3.5 is supplied by EPrints Services.

=end COPYRIGHT_AND_LICENSE
