#!/bin/bash

# Deletes PID files for OpenOffice, if the processes did not clear them properly on reboot.
openoffice_pid="../var/openoffice.pid"
openoffice_cmd="soffice"

cd `dirname $0`
if [[ -f $openoffice_pid && ! -d /proc/`cat $openoffice_pid` ]]; then
    rm $openoffice_pid
elif [[ -f $openoffice_pid && -d /proc/`cat $openoffice_pid` && "`cat /proc/\`cat $openoffice_pid\`/cmdline | tr -d '\0'`" != *"$openoffice_cmd"* ]]; then
    rm $openoffice_pid
fi
